package model;
// Generated Jan 3, 2016 7:01:35 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetailPesanan generated by hbm2java
 */
@Entity
@Table(name="detail_pesanan"
    ,catalog="restoran"
)
public class DetailPesanan  implements java.io.Serializable {


     private Integer idDetailPesanan;
     private Menu menu;
     private Pesanan pesanan;
     private int jumlah;

    public DetailPesanan() {
    }

    public DetailPesanan(Menu menu, Pesanan pesanan, int jumlah) {
       this.menu = menu;
       this.pesanan = pesanan;
       this.jumlah = jumlah;
    }
    
    public DetailPesanan(Menu menu ,int jumlah) {
       this.menu = menu;
       this.jumlah = jumlah;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_detail_pesanan", unique=true, nullable=false)
    public Integer getIdDetailPesanan() {
        return this.idDetailPesanan;
    }
    
    public void setIdDetailPesanan(Integer idDetailPesanan) {
        this.idDetailPesanan = idDetailPesanan;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_menu", nullable=false)
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pesanan", nullable=false)
    public Pesanan getPesanan() {
        return this.pesanan;
    }
    
    public void setPesanan(Pesanan pesanan) {
        this.pesanan = pesanan;
    }

    
    @Column(name="jumlah", nullable=false)
    public int getJumlah() {
        return this.jumlah;
    }
    
    public void setJumlah(int jumlah) {
        this.jumlah = jumlah;
    }




}


