package model;
// Generated Jan 10, 2016 3:08:15 PM by Hibernate Tools 4.3.1



/**
 * DetailPesanan generated by hbm2java
 */
public class DetailPesanan  implements java.io.Serializable {


     private Integer idDetailPesanan;
     private Menu menu;
     private Pesanan pesanan;
     private int jumlah;

    public DetailPesanan() {
    }

    public DetailPesanan(Menu menu, Pesanan pesanan, int jumlah) {
       this.menu = menu;
       this.pesanan = pesanan;
       this.jumlah = jumlah;
    }
    
    public DetailPesanan(Menu menu, int jumlah) {
       this.menu = menu;
       this.jumlah = jumlah;
    }
   
    public Integer getIdDetailPesanan() {
        return this.idDetailPesanan;
    }
    
    public void setIdDetailPesanan(Integer idDetailPesanan) {
        this.idDetailPesanan = idDetailPesanan;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public Pesanan getPesanan() {
        return this.pesanan;
    }
    
    public void setPesanan(Pesanan pesanan) {
        this.pesanan = pesanan;
    }
    public int getJumlah() {
        return this.jumlah;
    }
    
    public void setJumlah(int jumlah) {
        this.jumlah = jumlah;
    }




}


