package model;
// Generated Jan 10, 2016 3:08:15 PM by Hibernate Tools 4.3.1



/**
 * Meja generated by hbm2java
 */
public class Meja  implements java.io.Serializable {


     private Integer noMeja;
     private String kategori;
     private int lantai;
     private int status;
     private int kapasitas;

    public Meja() {
    }

    public Meja(String kategori, int lantai, int status, int kapasitas) {
       this.kategori = kategori;
       this.lantai = lantai;
       this.status = status;
       this.kapasitas = kapasitas;
    }
   
    public Integer getNoMeja() {
        return this.noMeja;
    }
    
    public void setNoMeja(Integer noMeja) {
        this.noMeja = noMeja;
    }
    public String getKategori() {
        return this.kategori;
    }
    
    public void setKategori(String kategori) {
        this.kategori = kategori;
    }
    public int getLantai() {
        return this.lantai;
    }
    
    public void setLantai(int lantai) {
        this.lantai = lantai;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public int getKapasitas() {
        return this.kapasitas;
    }
    
    public void setKapasitas(int kapasitas) {
        this.kapasitas = kapasitas;
    }




}


