package model;
// Generated Jan 10, 2016 3:08:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private Integer idMenu;
     private String namaMenu;
     private String jenis;
     private int stok;
     private Double harga;
     private Set detailPesanans = new HashSet(0);

    public Menu() {
    }

	
    public Menu(String namaMenu, String jenis, int stok, Double harga) {
        this.namaMenu = namaMenu;
        this.jenis = jenis;
        this.stok = stok;
        this.harga = harga;
    }
    public Menu(String namaMenu, String jenis, int stok, Double harga, Set detailPesanans) {
       this.namaMenu = namaMenu;
       this.jenis = jenis;
       this.stok = stok;
       this.harga = harga;
       this.detailPesanans = detailPesanans;
    }
   
    public Integer getIdMenu() {
        return this.idMenu;
    }
    
    public void setIdMenu(Integer idMenu) {
        this.idMenu = idMenu;
    }
    public String getNamaMenu() {
        return this.namaMenu;
    }
    
    public void setNamaMenu(String namaMenu) {
        this.namaMenu = namaMenu;
    }
    public String getJenis() {
        return this.jenis;
    }
    
    public void setJenis(String jenis) {
        this.jenis = jenis;
    }
    public int getStok() {
        return this.stok;
    }
    
    public void setStok(int stok) {
        this.stok = stok;
    }
    public Double getHarga() {
        return this.harga;
    }
    
    public void setHarga(Double harga) {
        this.harga = harga;
    }
    public Set getDetailPesanans() {
        return this.detailPesanans;
    }
    
    public void setDetailPesanans(Set detailPesanans) {
        this.detailPesanans = detailPesanans;
    }




}


