package model;
// Generated Jan 3, 2016 7:01:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pesanan generated by hbm2java
 */
@Entity
@Table(name="pesanan"
    ,catalog="restoran"
)
public class Pesanan  implements java.io.Serializable {


     private int idPesanan;
     private Date waktu;
     private int noMeja;
     private String status;
     private Set detailPesanans = new HashSet(0);

    public Pesanan() {
    }

	
    public Pesanan(int idPesanan, Date waktu, int noMeja, String status) {
        this.idPesanan = idPesanan;
        this.waktu = waktu;
        this.noMeja = noMeja;
        this.status = status;
    }
    public Pesanan(int idPesanan, Date waktu, int noMeja, String status, Set detailPesanans) {
       this.idPesanan = idPesanan;
       this.waktu = waktu;
       this.noMeja = noMeja;
       this.status = status;
       this.detailPesanans = detailPesanans;
    }

    public Pesanan(Date waktu, int noMeja, String status) {
        this.waktu = waktu;
        this.noMeja = noMeja;
        this.status = status;
    }
    
    
   
     @Id 

    
    @Column(name="id_pesanan", unique=true, nullable=false)
    public int getIdPesanan() {
        return this.idPesanan;
    }
    
    public void setIdPesanan(int idPesanan) {
        this.idPesanan = idPesanan;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="waktu", nullable=false, length=19)
    public Date getWaktu() {
        return this.waktu;
    }
    
    public void setWaktu(Date waktu) {
        this.waktu = waktu;
    }

    
    @Column(name="no_meja", nullable=false)
    public int getNoMeja() {
        return this.noMeja;
    }
    
    public void setNoMeja(int noMeja) {
        this.noMeja = noMeja;
    }

    
    @Column(name="status", nullable=false, length=2)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pesanan")
    public Set getDetailPesanans() {
        return this.detailPesanans;
    }
    
    public void setDetailPesanans(Set detailPesanans) {
        this.detailPesanans = detailPesanans;
    }




}


