package model;
// Generated Jan 10, 2016 3:08:15 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pesanan generated by hbm2java
 */
public class Pesanan  implements java.io.Serializable {


     private Integer idPesanan;
     private Date waktu;
     private int noMeja;
     private String status;
     private Set detailPesanans = new HashSet(0);

    public Pesanan() {
    }

	
    public Pesanan(Date waktu, int noMeja, String status) {
        this.waktu = waktu;
        this.noMeja = noMeja;
        this.status = status;
    }
    public Pesanan(Date waktu, int noMeja, String status, Set detailPesanans) {
       this.waktu = waktu;
       this.noMeja = noMeja;
       this.status = status;
       this.detailPesanans = detailPesanans;
    }
   
    public Integer getIdPesanan() {
        return this.idPesanan;
    }
    
    public void setIdPesanan(Integer idPesanan) {
        this.idPesanan = idPesanan;
    }
    public Date getWaktu() {
        return this.waktu;
    }
    
    public void setWaktu(Date waktu) {
        this.waktu = waktu;
    }
    public int getNoMeja() {
        return this.noMeja;
    }
    
    public void setNoMeja(int noMeja) {
        this.noMeja = noMeja;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getDetailPesanans() {
        return this.detailPesanans;
    }
    
    public void setDetailPesanans(Set detailPesanans) {
        this.detailPesanans = detailPesanans;
    }




}


